### ISSUE TITLE
Error RuntimeError: new_Decoder returned

### ISSUE THREAD

**Issue by sabas1080** [bambocher/pocketsphinx-python#10]
Hi

I have the next error

```
Traceback (most recent call last):
  File "beagleman.py", line 80, in <module>
    decoder = Decoder(config)
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 266, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1
```

Thanks

**Comment by nshmyrev** [comment]
This error means you configured decoder incorrectly, for example, you incorrectly specified the path to the acoustic model. More details about error most be provided in the log. You can reenable logging and run the module again to get more information on what exactly went wrong.

**Comment by sabas1080** [comment]
Yes, thanks

**Comment by evadaddy2010** [comment]
I have the same problem. im using the mycroft 8.b image and this happens every time.
