### ISSUE TITLE
Getting error while running sample program from repo.

### ISSUE THREAD

**Issue by MayankPratap** [bambocher/pocketsphinx-python#12]
My python version is 2.7.9 and I am running this program on Ubuntu 15.04 

"ERROR: "acmod.c", line 83: Folder 'pocketsphinx/model/en-us/en-us' does not contain acoustic model definition 'mdef'
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    decoder = Decoder(config)
  File "/usr/local/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 271, in **init**
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1 "

**Comment by bambocher** [comment]
Try this snippet.

In the terminal:

```bash
sudo apt-get install -qq python python-dev python-pip build-essential swig git libpulse-dev
sudo pip install --upgrade pip setuptools wheel pocketsphinx
```

In ipython or python:

```python
from pocketsphinx import Pocketsphinx
print(Pocketsphinx().decode())
```
