### ISSUE TITLE
v0.1.1 reports `ImportError: No module named '_sphinxbase'`

### ISSUE THREAD

**Issue by feigaoxyz** [bambocher/pocketsphinx-python#14]
v0.1.1 reports `ImportError: No module named '_sphinxbase'` on example code in README.
v0.1.0 works well.

Check [this gist](https://gist.github.com/feigaoxyz/af5d93660911d86cbece3ccb3784747b) for output.

I am running brew Python3.5 on macOS 10.12 if that matters.

**Comment by fbacker** [comment]
Looks as same bugg https://github.com/bambocher/pocketsphinx-python/issues/15

**Comment by bambocher** [comment]
Sorry for the long answer. In 0.1.1 really had a problem on Mac OS X. Please try the new version 0.1.3. It fixed this problem. Also added higher-level classes. Examples can be seen [here](https://github.com/bambocher/pocketsphinx-python). I hope they will be useful. 1.1.0 removed from PyPI.
