### ISSUE TITLE
Python pocketsphinx 'module' object has no attribute 'Decoder'

### ISSUE THREAD

**Issue by Arti3DPlayer** [bambocher/pocketsphinx-python#3]
I try to run simple example of using pocketsphinx. I have installed all libraries, plugins that was needed... Python 2.7.6. But still get an error: 

> pocketsphinx 'module' object has no attribute 'Decoder'

    import sys,os 
    import pocketsphinx as ps 
    import sphinxbase
    
    
    def decodeSpeech(hmmd,lmdir,dictp,wavfile):
        speechRec = ps.Decoder(hmm = hmmd, lm = lmdir, dict = dictp)
        wavFile = file(wavfile,'rb')
        wavFile.seek(44)
        speechRec.decode_raw(wavFile)
        result = speechRec.get_hyp()
        return result[0]
    
    
    if __name__ == "__main__":
        hmdir = '/usr/share/pocketsphinx/model/hmm/wsj1'
        lmd   = '/usr/share/pocketsphinx/model/lm/wsj/wlist5o.3e-7.vp.tg.lm.DMP'
        dictd = '/usr/share/pocketsphinx/model/lm/wsj/wlist5o.dic'
        wavfile = "msg_12c3da80-c6be-11e3-9430-eb6ba5ab4d1f.wav"
        recognised = decodeSpeech(hmdir,lmd,dictd,wavfile)

**Comment by Arti3DPlayer** [comment]
```print dir(ps)```
```['builtins', 'doc', 'file', 'loader', 'name', 'package', 'path']```

```print ps.__file__```

```
/usr/local/lib/python2.7/dist-packages/pocketsphinx-0.0.4-py2.7-linux-x86_64.egg‌​/pocketsphinx/__init__.pyc```

**Comment by sebpiq** [comment]
Same error here :(

**Comment by sebpiq** [comment]
And from ipython the import sometimes work (and I get the `Decoder`), sometimes I receive the error `ValueError: PyCapsule_GetPointer called with invalid PyCapsule object`

**Comment by sidja** [comment]
Same here

**Comment by nshmyrev** [comment]
PyCapsule error means you are using very outdated pocketsphinx version 0.8. Please use latest version.

**Comment by Virenferns** [comment]
I am facing this error while running this code: 
**TypeError: __init__() got an unexpected keyword argument 'hmm'**


CODE:
from os import environ, path
import sys,os
import pocketsphinx as ps 
import sphinxbase
print (dir(ps))


MODELDIR = "C:\\Anaconda3\\Lib\\site-packages\\pocketsphinx\\model"
DATADIR = "C:\\Anaconda3\\Lib\\site-packages\\pocketsphinx\\data"

def decodeSpeech(hmmd,lmdir,dictp,wavfile):
    speechRec = ps.Decoder(hmm = hmmd, lm = lmdir, dict = dictp)
    wavFile = os(wavfile,'rb')
    wavFile.seek(44)
    speechRec.decode_raw(wavFile)
    result = speechRec.get_hyp()
    return result[0]


if __name__ == "__main__":
    hmdir = path.join(MODELDIR, 'en-us/en-us')
    lmd   = path.join(MODELDIR, 'en-us/en-us.lm.bin')
    dictd = path.join(MODELDIR, 'en-us/cmudict-en-us.dict')
    wavfile = path.join(DATADIR, 'goforward.raw')
    recognised = decodeSpeech(hmdir,lmd,dictd,wavfile)

**Comment by sairajreddy** [comment]
`from __future__ import print_function
import os
from pocketsphinx import Pocketsphinx, get_model_path, get_data_path
 
model_path = '/Users/.../Pocket_Sphinx/pocketsphinx-5prealpha/model/en-in/' 
data_path = '/Users/.../Downloads/Audio/..'

config = {
 'hmm': os.path.join(model_path, 'en-in'),
 'lm': os.path.join(model_path, 'words.lm'),
 'dict': os.path.join(model_path, 'fa_in.dic')
 }
 
ps = Pocketsphinx(**config)
ps.decode(
 audio_file=os.path.join(data_path, '<File>.wav'),
 buffer_size=2048,
 no_search=False,
 full_utt=False
 )
print(ps.segments())
print(*ps.best(count=20), sep='\n')`

This results in :

```
Traceback (most recent call last):
  File "fa2.py", line 14, in <module>
    ps = Pocketsphinx(**config)
  File "/usr/local/lib/python2.7/site-packages/pocketsphinx/__init__.py", line 90, in __init__
    super(Pocketsphinx, self).__init__(config)
  File "/usr/local/lib/python2.7/site-packages/pocketsphinx/pocketsphinx.py", line 273, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1
```

Request @bambocher to re-open this issue.
