### ISSUE TITLE
ALSA support request for Matrix Voice RaspberryPi Extension Board

### ISSUE THREAD

**Issue by spacemunkey77** [bambocher/pocketsphinx-python#32]
Would it be possible to enable ALSA support for boards that do not currently work with Pulse audio like the Matrix Voice (https://www.matrix.one/products/voice) ?

**Comment by Svetlana91** [comment]
Already an issue with number #29   
https://github.com/bambocher/pocketsphinx-python/issues/29
  
So you can close this.
