### ISSUE TITLE
Decoder.default_config() doesn't exist

### ISSUE THREAD

**Issue by sebpiq** [bambocher/pocketsphinx-python#5]
`Decoder` doesn't seem to have a `default_config` method.

**Comment by aurashn** [comment]
Is this the common error we are noticing?

Traceback (most recent call last):
  File "example.py", line 12, in <module>
    config = Decoder.default_config()
NameError: name 'Decoder' is not defined

**Comment by sebpiq** [comment]
No that's another one :)

I managed to import `Decoder` by importing in ipython. And then I got the error above.

**Comment by bambocher** [comment]
I think the problem is no longer relevant.
