### ISSUE TITLE
Trouble installing on Mac OS Big Sur 11.0.1 "fatal error: 'al.h' file not found"

### ISSUE THREAD

**Issue by ngulya** [bambocher/pocketsphinx-python#67]
Some trouble with installation on new Mac OS version
`python3 -m pip install --upgrade pocketsphinx
`
and get:
........
deps/sphinxbase/src/libsphinxad/ad_openal.c:43:10: fatal error: 'al.h' file not found
    #include <al.h>
             ^~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1

and if install from GitHub directly (Install with distutils) with changing al.h to OpenAL/al.h (and same for alc) get this
........
gcc -bundle -undefined dynamic_lookup -arch x86_64 -g build/temp.macosx-10.9-x86_64-3.7/swig/sphinxbase/ad_openal_wrap.o build/temp.macosx-10.9-x86_64-3.7/deps/sphinxbase/src/libsphinxad/ad_openal.o /System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL -o build/lib.macosx-10.9-x86_64-3.7/sphinxbase/_ad_openal.cpython-37m-darwin.so
clang: error: no such file or directory: '/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL'
error: command 'gcc' failed with exit status 1

**Comment by ShivanshRakesh** [comment]
Hey, I'm facing the same issue. I'm running MacOS 11.0.1 (Darwin 20.1.0).

**Comment by jalemann** [comment]
@ShivanshRakesh Thank you, this finally did the trick for me!

**Comment by xrisk** [comment]
For anyone who isn’t using Xcode but only the CLT, the appropriate path to use is: `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenAL.framework`

**Comment by jalemann** [comment]
@xrisk That didn't work for me. How did you install OpenAL?

**Comment by xrisk** [comment]
@jalemann what I meant is that you have to modify the paths in @ShivanshRakesh's comment in case you don't have the entire Xcode (but only the CLT). In addition, you have to implement the changes in #28, there are two modifications to be made in the source code.

As for, the CLT itself -- you can get it from https://developer.apple.com/downloads/index.action (please note: you don't need this if you have Xcode installed).

**Comment by jalemann** [comment]
@xrisk Nvm did something wrong on the first attempt, did work now (same macOS and CLT versions). Thank you.

**Comment by victorC97** [comment]
Hi everyone,

I'm on Big Sur and of course I encounter some issues while using pocketsphinx with Python... I followed your previous advices (changing al.h to OpenAL/al.h and Xcode trick to have Headers and openAL.tbd) and manage to install the package.

However I have now : 
`ImportError: dlopen(/usr/local/lib/python3.9/site-packages/sphinxbase/_ad_openal.cpython-39-darwin.so, 2): Symbol not found: _alcCaptureCloseDevice
  Referenced from: /usr/local/lib/python3.9/site-packages/sphinxbase/_ad_openal.cpython-39-darwin.so
  Expected in: flat namespace
 in /usr/local/lib/python3.9/site-packages/sphinxbase/_ad_openal.cpython-39-darwin.so`

I don't know what is it refering to, probably a library link ?

Can someone help me with this please ? Thank you.

**Comment by TirtharajPramanik** [comment]
> Hey, I'm facing the same issue. I'm running MacOS 11.0.1 (Darwin 20.1.0). I tried the fix mentioned at [#28 (comment)](https://github.com/bambocher/pocketsphinx-python/issues/28#issuecomment-334493324) but it didn't help.
> 
> Apparently, there is no file/directory: `/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL`.
> 
> [EDIT] I fixed the issue by making these changes:
> 
> #### Followed the steps mentioned at [#28 (comment)](https://github.com/bambocher/pocketsphinx-python/issues/28#issuecomment-334493324).
> #### Made the following changes in `<project_root>/setup.py`:
> * Changed **line 235**: `sb_include_dirs.append('/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers')` to
> 
> ```
> sb_include_dirs.append('/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers')
> ```
> 
>  * Changed **line 242**: `extra_objects=['/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL'],` to
> 
> ```
> extra_objects=['/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL.tbd'],
> ```

Thank you so much bro.
I was scratching my head for hours.

**Comment by jonahpearl** [comment]
> 

Works on OS X 12.0.1, with just CLT installed :D

**Comment by jonahpearl** [comment]
> For anyone who isn’t using Xcode but only the CLT, the appropriate path to use is: `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenAL.framework/Versions/A`
> 
> (Tested on macOS 11.1, CLT version 12.3.0.0.1.1607026830)

Worked on macOS 12.0.1, thank you!

**Comment by LOTEAT** [comment]
Very useful, thank you very much!

**Comment by florrietan** [comment]
> Hey, I'm facing the same issue. I'm running MacOS 11.0.1 (Darwin 20.1.0). I tried the fix mentioned at [#28 (comment)](https://github.com/bambocher/pocketsphinx-python/issues/28#issuecomment-334493324) but it didn't help.
> 
> Apparently, there is no file/directory: `/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL`.
> 
> [EDIT] I fixed the issue by making these changes:
> 
> #### Followed the steps mentioned at [#28 (comment)](https://github.com/bambocher/pocketsphinx-python/issues/28#issuecomment-334493324).
> #### Made the following changes in `<project_root>/setup.py`:
> * Changed **line 235**: `sb_include_dirs.append('/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers')` to
> 
> ```
> sb_include_dirs.append('/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenAL.framework/Versions/A/Headers')
> ```
> 
> * Changed **line 242**: `extra_objects=['/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL'],` to
> 
> ```
> extra_objects=['/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenAL.framework/Versions/A/OpenAL.tbd'],
> ```

OMG this worked! Thank you a lot!!!
