### ISSUE TITLE
Creating a "Decoder" object takes much longer than usual

### ISSUE THREAD

**Issue by rcbyron** [bambocher/pocketsphinx-python#7]
Using this configuration, 

    config = Decoder.default_config()
    config.set_string('-logfn', os.path.join(settings.LOGS_DIR, 'passive-listen.log'))
    config.set_string('-hmm', os.path.join(settings.MODEL_DIR, 'en-us\en-us'))
    config.set_string('-lm', os.path.join(settings.MODEL_DIR, 'en-us\en-us.lm.dmp'))
    config.set_string('-dict', os.path.join(settings.MODEL_DIR, 'en-us\cmudict-en-us.dict'))
    config.set_string('-kws_threshold', '1e-50')
    
    decoder = Decoder(config) # This line takes quite a few seconds

Any idea why? On Python 3.4 using pocketsphinx 0.0.8 this line ran in less than 1 second.

**Comment by nshmyrev** [comment]
It is probably loading dmp language model. In new versions a different binary format for lm is used, it takes time to convert dmp to binary. You can load latest binary lm instead.

**Comment by rcbyron** [comment]
Thanks for the quick response! That fixed the issue :)
