### ISSUE TITLE
Decoder Error

### ISSUE THREAD

**Issue by jhoelzl** [bambocher/pocketsphinx-python#8]
I have installed all libraries on Ubuntu 14.04.

When i run the test script, i get this error:

`File "test_cmu.py", line 4, in <module>
    from pocketsphinx.pocketsphinx import *
  File "sphinxbase.pxd", line 150, in init pocketsphinx (pocketsphinx.c:7935)
ValueError: PyCapsule_GetPointer called with invalid PyCapsule object`

Can you help me with that? 

Thanks,
Josef

**Comment by nshmyrev** [comment]
Update pocketsphinx and sphinxbase, you are using very outdated version.

**Comment by jhoelzl** [comment]
Hi @nshmyrev, thanks for helping, how should i do this?

I tried 
```
sudo apt-get install -y python python-dev python-pip build-essential swig git
sudo pip install pocketsphinx --upgrade`
```
but error is still existent.

I also followed the install instructions:

```
sudo apt-get install -y python python-dev python-pip build-essential swig git
git clone --recursive https://github.com/bambocher/pocketsphinx-python
cd pocketsphinx-python
sudo python setup.py install
```

but does not help

**Comment by nshmyrev** [comment]
You have old sphinxbase module installed with debian package, probably sphinxbase-0.8. You need to uninstall it.

**Comment by jhoelzl** [comment]
Thanks, now it works!
